import LinguisticsArticles from "../../../Articles/LinguisticsArticles/LinguisticsArticles";

const LinguisticsScope = () => {
    return (
        <div className="w-full">
            <h2 className="text-xl font-bold text-[#91000D]">Aims & Scope</h2>

            <div className="flex items-center py-8 gap-24">
                <p>
                    The Sounds and Words of Language,
                    Structures and Meanings,
                    Language and Gender,
                    Sociolinguistics,
                    English Syntax,
                    Historical Linguistics,
                    Origins/Evolution of Language,
                    Experimental Linguistics,
                    Phonology,
                    Endangered/Minority Languages,
                    Language and Nature,
                    Communicative Strategies,
                    Linguistic Anthropology,
                    Linguistic Analysis,
                    Language and Alienation,
                    Hispanic Linguistics,
                    Analyzing Chinese Language,
                    Philosophy of Language,
                    Psychology of Language,
                    Field Methods in Linguistics,
                    History of the Spanish Language,
                    Spanish Dialectology,
                    Applied Linguistics,
                    Language, Brain and Society,
                    Advertising and Propaganda,
                    Phonetics,
                    Morphology,
                    Syntax,
                    Semantics and Pragmatics,
                    Historical Linguistics,
                    History of Ideas on Language,
                    History of English/History of French,
                    Language Acquisition,
                    Psychology of Language Processing and Learning,
                    Language Typology,
                    Communication Theory,
                    Freedom of Communication,
                    Principles of Argumentation,
                    Forensics,
                    Analysis and Briefing,
                    Gender and Communication,
                    Conflict and Communication,
                    Current Problems in Evolution and Communication,
                    Nonverbal Communication and Body Language,
                    Understanding Relationships,
                    Dyadic Communication and Interpersonal Relationships,
                    Communication and Conflict in Couples and Families,
                    Negotiation,
                    Language and Music,
                    Voice & Its Perception,
                    Group Communication,
                    Talk and Mass Communication,
                    Promoting Dialogue Across Diverse Worlds,
                    Talk and the Body,
                    Psychology of Language and Gender,
                    Talk and Social Institutions,
                    Evolution of Interpersonal Communication,
                    Animal Communication,
                    Entertainment as Implicit Pedagogy,
                    The Gaming Mind,
                    Cultural Factors in Interpersonal Communication,
                    Culture vs. Media,
                    Multicultural Television,
                    Decoding Media Strategies,
                    Narrative in Mass Communication,
                    Media Portrayals of Gays and Lesbians,
                    Transnational Bollywood,
                    Political Marketing,
                    Speech and the Law,
                    Theory of Persuasive Communication,
                    Films of Persuasion,
                    Rhetoric of Popular Culture,
                    Conversational Structures,
                    Situation Comedy and American Culture,
                    Evolution of Mass Media Images,
                    Sociology of Mass Communication,
                    Marketing, Advertising and Human Nature,
                    Media and Gender, Race, Class & Sexuality,
                    Methodologies in Communication Research,
                    Computer-Mediated Communication,
                    Analysis of Communication Effects,
                    The Media and Aggression against Women,
                    Social Communication and the New Technology,
                    Social Impact of the New Electronic Media,
                    Social Networking,
                    Celebrity, Fame, and Social Media,
                    Evolution of Communication Technology,
                    Pornography and Evolution,
                    Political Communication,
                    Electoral Politics and Mass Media,
                    Presidential Communication,
                    Public Diplomacy,
                    Entertainment Law,
                    Agitational Communication,
                    Communicative Dynamics in Film and TV Production,
                    Free Speech in Advertising,
                    Critical Vision,
                    Legal Communication,
                    Theories of Freedom of Speech and Press,
                    Free Speech in Workplace,
                    Communicating Complex Policy,
                    Trial by Jury,
                    Criticism and the Public Arts,
                    Visual Communication and Social Advocacy,
                    Libel and Freedom of Expression,
                    Propaganda & the Media,
                    Politics of Censorship,
                    Non Verbal Communication,
                    Mass Media, Public Opinion, & Foreign Policy,
                    Ethical and Policy Issues in Institutions of Mass Communication,
                </p>
            </div>

            <div className='py-2'>
                <h2 className='font-medium text-[#91000D] py-2'>Current Issue:</h2>
                <div>
                        <LinguisticsArticles></LinguisticsArticles>
                </div>
            </div>
        </div>
    );
};

export default LinguisticsScope;