import GenderArticles from "../../../Articles/GenderArticles/GenderArticles";


const GenderScope = () => {
    return (
        <div className="w-full">
            <h2 className="text-xl font-bold text-[#91000D]">Aims & Scope</h2>

            <div className="flex items-center py-8 gap-24">
                <p>
                    Women, Culture, and Society,
                    Women's Leadership,
                    Women Working in the Global Economy,
                    Feminist Practices,
                    Gender, Culture, and Representation,
                    Dynamics of Class, Race, and Sex,
                    Gender and Science,
                    Gender, Art & Society,
                    The Modern Girl,
                    Critical Study of Masculinities,
                    Lesbians and Gay Men and Society,
                    Critical Sexuality Studies,
                    Mentoring Leadership & Practices,
                    Feminist Theory: Historical Provocations,
                    Feminist Theory: Contemporary Engagements,
                    Contemporary Feminisms,
                    Women and the Law,
                    South Asian Feminism,
                    African Feminism,
                    Gender and Consumption,
                    The Gendered Body,
                    Same Sex Desire, Culture, and Representation,
                    Psychology of Women and Gender,
                    Race, Gender, Nation,
                    Memoir and Autobiography,
                    Theorizing Gender and Sexuality,
                    The Color of AIDS: The Politics of Race during the AIDS Crisis,
                    Power, Subjectivity and Resistance in US & Globally,
                    Transnational Sexualities,
                    Research on Sexuality,
                    Gender & Popular Culture,
                    Women and Leadership,
                    Gender and Spirituality,
                    Race, Gender, Class and Sexualities,
                    Feminism, Space, and Visuality,
                    Critical Feminist Investigation,
                    Making Change,
                    Contemporary Feminist Activism,
                    The Culture of American Women,
                    Women Writing Culture,
                    Race, Class, Gender and Schooling,
                    The Anthropology of Gender,
                    Gender & Power in Africa,
                    Women Artists,
                    Women and Art,
                    Women in Antiquity,
                    Ethnography of Gender in South Asia,
                    Women's Traditions in Literature,
                    Women and the Economy,
                    Women's Work and Labor Markets,
                    Drama by Women,
                    Fiction by Women,
                    Poetry by Women,
                    Autobiography by Women,
                    Gender and Genre,
                    Issues and Problems in Feminist Literary Studies,
                    Feminist Theory in Literary Study,
                    Theories of Gender and Sexuality,
                    Theories of Women and Film,
                    20th-Century Feminisms,
                    Gender Geographies,
                    Matriarchy and Modenity,
                    The Changing Image of Women in German Literature,
                    The Women in Judaism,
                    History of Feminism,
                    History of Jewish Women,
                    Women and Society in the Islamic Middle East,
                    Israeli Women,
                    Feminism, Signs & Representation,
                    Thinking Bodies,
                    Black Women in the United States,
                    Race, Gender, Media, and the Law,
                    Topics in Women's & Gender Studies,
                    Freud & Feminism,
                    Gender and Human Rights,,
                    Women, Work, and Social Change,
                    Women’s Global Health Movements,
                    Impacts of Economic Inequality on Women’s Health,
                    The Growth Imperative, Global Ecology, and Women’s Health,
                    Debt, Crisis, and Women’s Health,
                    Gendered Health Impacts of Structural Adjustment Programs,
                    Health Consequences of Global Trade in Food Commodities,
                    Health Consequences of Global Trade in Pharmaceuticals,
                    Gendered Professions and the Transnational Care Economy,
                    Women’s Global Health,
                    Ethics and Women’s Leadership,
                    Feminism & Visual Cultures,
                    Feminism, Policy, and the Poor,
                    Gender, Development, Environment,
                    The Black Woman,
                    Women Writers,
                    Issues and Methods in Feminist Literary Studies,
                    Women in Europe and the Americas Until 1800,
                    Women in Europe and the United States Since 1800,
                    History of Witchcraft and Magic,
                    The Latin American Woman,
                    Gender across Cultures,
                    Sociology of Women,
                    Sociology of the Family,
                    The Black Woman in Political Context,
                    The Black Family,
                    Women on the Fringe,
                    Women in Chinese History,
                    Male and Female in American History,
                    Women in Italian Literature and Society,
                    Israeli Women: Historical & Literary Perspectives,
                    Jewish-American Women,
                    History of Jewish Women,
                    Yiddish Literature from Tradition to Enlightenment,
                    Women in Jewish Law,
                    Japanese Women Writers,,
                    Working Women in American Society,
                    Women and the Labor Movement,
                    Philosophical Issues in Feminism,
                    Women and American Politics,
                    Women and Public Policy,
                    Gender and Political Theory,
                    Contemporary Feminist Theory,
                    Gender and Political Economy,
                    Gender, Public Policy, & Law,
                    Psychology of Sex and Gender,
                    Psychology of Women,
                    Queer Culture in Hispanic Caribbean & its Diasporas,
                    Latinas: Migration, Work, and Family,
                    U.S. Latina Feminists,
                    Women in Religion,
                    Feminists Theology,
                    Social Construction of Gender & Sexuality in Russian Lit,
                    Sociology of Gender,
                    Third World Women,
                    Sexuality of Society,
                </p>
            </div>

            <div className='py-2'>
                <h2 className='font-medium text-[#91000D] py-2'>Current Issue:</h2>
                <div>
                    <GenderArticles></GenderArticles>
                </div>
            </div>
        </div>
    );
};

export default GenderScope;