import EducationArticles from "../../../Articles/EducationArticles/EducationArticles";


const EducationScope = () => {
    return (
        <div className="w-full">
            <h2 className="text-xl font-bold text-[#91000D]">Aims & Scope</h2>

            <div className="flex items-center py-8 gap-24">
                <p>
                    Social Perspectives in Education, 
                    Secondary Music Education, 
                    Professional Engagement, 
                    Language and Literacy Learning in the, 
                    Culture, Identity and Education, 
                    Special Education, 
                    Professional Issues in Teaching, 
                    Managing the Classroom Environment, 
                    Ethnographic Methodology and Methods, 
                    Interventionist/Experimental Research Design and Analysis, 
                    Survey Research Design and Analysis, 
                    Educational Assessment and Measurement, 
                    Behaviour Management of Exceptional Students, 
                    Intellectual Disabilities, 
                    Advanced Professional Practice in Special Education, 
                    University Learning and Teaching, 
                    Student Learning in Higher,  
                    Enhancing Learning & Teaching in Higher Education, 
                    The Professional Teacher’s Ethics, 
                    Learner Diversity, 
                    Human Development and Education, 
                    Organisation Theory in Education, 
                    Legal, Industrial & Ethical Issues in Educational Leadership, 
                    Advanced TESOL Curriculum Design and Assessment, 
                    Advanced Professional Practice, 
                    Workplace Leadership Development Project,  
                    Educational Policy: Theory and Practice, 
                    Culture, Communication and the, 
                    Human Resource Management in Education, 
                    Literature Review in Education, 
                    Effective Schools, 
                    Identification of Gifted Children, 
                    Curriculum Differentiation & Assessment in Gifted Education, 
                    Social and Emotional Development of Intellectually Gifted Children, 
                    Chinese Method of Education, 
                    English Method of Education, 
                    English as a Second Language, 
                    French Method 2, 
                    Geography Method, 
                    German Method,  
                    Indonesian Method, 
                    Japanese, 
                    Science Double Method, 
                    Contemporary Issues in Language Education, 
                    Literature Review in Education, 
                    School-based Management & Accountability, 
                    Developing Programs for Gifted Children, 
                    Motivation in Learning and Teaching, 
                    Managing Learner Cognitive Load, 
                    Design and Evaluation of ICT-based Learning, 
                    Educational Leadership for Gifted Students, 
                    Teaching Oral Communication, 
                    Inclusive Education, 
                    Scaffolding ESL Learners in the Challenge Zone, 
                    Financial Issues in Educational Leadership, 
                    Assessment for Learning, 
                    Contemporary Issues in Educational Leadership, 
                    Teacher Leadership, 
                    Developing Effective Programmes for Gifted Students, 
                    Social and Political Contexts of Education, 
                    Music Education, 
                    Motivation in Teaching and Learning, 
                    Spanish Method, 
                    Business Studies Method, 
                    Economics Method, 
                    Korean Method, 
                    Legal Studies Method, 
                    Dance Method, 
                    Society and Culture Method, 
                    Social and Political Contexts of Education, 
                    Community, 
                    Educational Psychology, 
                    Professional Engagement, 
                    Learning and Teaching, 
                    Teacher Effectiveness, 
                    Human Variation and Education, 
                    Managing Learner Cognitive Load, 
                    e-learning, 
                    Psychology and Music, 
                    Managing the Classroom, 
                    Responding to Gifted and Talented Students, 
                    Teaching Method for High Incidence Disabilities, 
                    Developing a Performance Based Culture, 
                    Learning Psychological and Social Perspectives, 
                    Autism Spectrum Disorders, 
                    Investigating Issues in Curriculum and Assessment, 
                    Social and Political Contexts of Education, 
                    Community Engagement, 
                    Issues in First Year Teaching, 
                    Advanced Professional Practice Special Education, 
                    Qualitative Research: Critical Reading and Inquiry, 
                    Introduction to University Learning and Teaching, 
                    Student Learning in Higher Education, 
                    Educational Design for Learning in Higher Education, 
                    Coaching and mentoring in Educational Leadership, 
                    Communicative Disorders, 
                    Transitions in Lives of Students with Disabilities, 
                    Leadership in Action, 
                    Creating Engaging Learning Environment, 
                    Research in Science Education, 
                    Human Cognitive Architecture, 
                    Individual differences in Education, 
                    Motivation in Educational Settings, 
                    Evaluation of Educational Programs, 
                    Leadership Theory, Research and Practice, 
                    Advanced TESOL Methodology, 
                    Advanced Professional Practice, 
                    Workplace Leadership Development Project, 
                    Language and Literacy in the Classroom, 
                    Culture, Identity and Education, 
                    Educational Psychology, 
                    Music, 
                    Teacher Effectiveness, 
                    Human Variation and Education, 
                    eLearning and Technology-supported Teaching, 
                    Psychological Perspectives on Music Education, 
                    Interventionist and experimental design and analysis, 
                    Methods for Teaching Students with High Incidence Disabilities, 
                    Developing a Performance Based Culture, 
                    Coaching and Mentoring in Educational Leadership, 
                    Leadership in Action, 
                    Human Development & Education, 
                    Individual Differences and Education, 
                    Organisational Behaviour in Education, 
                </p>
            </div>

            <div className='py-2'>
                <h2 className='font-medium text-[#91000D] py-2'>Current Issue:</h2>
                <div>
                    <EducationArticles></EducationArticles>
                </div>
            </div>
        </div>
    );
};

export default EducationScope;