import SociologyArtics from "../../../Articles/SociologyArtics/SociologyArtics";

const SociologyScope = () => {
    return (
        <div className="w-full">
            <h2 className="text-xl font-bold text-[#91000D]">Aims & Scope</h2>

            <div className="flex items-center py-8 gap-24">
                <p>
                    Family and Society,
                    Issues and Problems in American Society,
                    World Society,
                    Global Information and Social Enterprise Studies,
                    Designing ICT Projects for Social Enterprise,
                    Project Implementation and Grant Writing for Social Entrepreneurs,
                    Designing Community Information Technology Centers,
                    Understanding Agile Web Development for Social Justice,
                    Statistical Methods,
                    The Logic and Methods of Social Inquiry,
                    Classical Sociological Theory,
                    Contemporary Sociological Theory,
                    Sports and Society,
                    Sustainable Design as Social Change,
                    Communication, Media, and Culture,
                    Popular Music, Social Practices, and Cultural Politics,
                    Sociology of Knowledge,
                    Gender, Sexuality, and Cultural Politics,
                    Sociology of Health and Medicine,
                    The Sociology of Law,
                    Law, Crime, and Social Justice,
                    Visual Sociology,
                    Visual Sociology Media Lab,
                    Society and Nature,
                    Sociology of Sex,
                    Drugs in Society,
                    Law and Politics in Contemporary Japan and East Asian Societies,
                    Race and Law,
                    The World Jury on Trial,
                    International Law and Global Justice,
                    Popular Culture and Cultural Studies,
                    Sociology of Food,
                    Media, Marketing, and Culture,
                    Sociology of Science and Technology,
                    Currents in African American Cultural Politics,
                    Television and the Nation,
                    Social Psychology,
                    Deviance and Conformity,
                    Field Research Methods,
                    Social Psychology of Power,
                    Group Process,
                    Language and Social Interaction,
                    Conversation Analysis,
                    Sociology of Sex,
                    Sociology of Violence, War, and Peace,
                    Work and Labor Markets in the New Economy,
                    Theory and Method in the Sociology of Marx,
                    Inequality and Identity,
                    Cross-National and Cross-Cultural Research,
                    Race and Ethnicity,
                    Feminist Theory,
                    Class, Culture, and Movement,
                    Race and Class,
                    Feminisms and Cultural Politics,
                    Course Design and Grant-Writing Seminar,
                    Symbolic Interactionism and Sociology of Emotions,
                    Race, Crime, and Justice,
                    Engaging Cultural Studies,
                    Urban Sociology,
                    Colonialism, International Law, and Global Justice,
                    Global Lay Justice Systems and Direct Democracy,
                    Culture, Knowledge, Power,
                    Sociology of Knowledge,
                    Cultural Practice and Everyday Life,
                    Cultural Politics of Difference,
                    Science, Technology, and Medicine,
                    Science and Justice,
                    Social Policy Research,
                    Writing for Social Scientists,
                    History and Philosophy of Social Work,
                    Sex and Gender,
                    Sociology of Death and Dying,
                    Body and Society,
                    Sociology of Emotions,
                    Cross-National and Cross-Cultural Research,
                    Political Consciousness,
                    Sexualities and Society,
                    Politics of Sex Work and Erotic Labor,
                    Global Corporations and National States,
                    Marx and Marxist Theory,
                    World Systems Perspective,
                    Economics for Non-Economists,
                    Development and Underdevelopment,
                    Social Justice,
                    Social Inequality,
                    Ethnic and Status Groups,
                    Exploring Global Inequality,
                    Sociology of Social Movements,
                    Water,
                    Twenty-First-Century African American Social Structure,
                    Women and Work,
                    Work and Society,
                    Urban Sociology,
                    Latinos/as and the American Global City,
                    Eco-Metropolis,
                    Global Cities,
                    Upper Division,
                    Sociology of Social Problems,
                    Nature, Poverty, and Progress,
                    Nature, Poverty, and Progress Laboratory,
                    Social Movements of the 1960s,
                    Hunger and Famine,
                    Feminist Theory,
                    Religion and Social Change,
                    Social Change in the Global Economy,
                    Global Islam: Politics, Movements, Discourses,
                    Sociology Teaching Practicum,
                    Contemporary Sociological Theory,
                    Sociological Methods,
                    Methods of Quantitative Analysis,
                    Field Research Methods,,
                    Comparative Historical Methods,
                    The Analysis of Cultural Forms,
                    Global Transformation,
                    Political Sociology,
                    Sociology of the Environment,
                    Globalization,
                    Political Economy for Sociologists,
                    Learning from Environmental Historians,
                    Theory and Practice of Social Work,
                    Human Behavior and the Social Environment,
                    Methods of Social Work Research,
                    Social Policy,
                    Psychopathology and Human Behavior,
                    Clinical Supervision and Program Management,
                    Social Work Practice Research,
                    Social Work and the Law,
                    Child Welfare Policy,
                    Practice with Older Adults and Their Families,
                    Family Resilience and Diversity,,
                    Progressive Social Work,
                    The Spiritual Dimension of Social Work Practice,
                    Grief Counseling and Therapy,
                    Clinical Practice with Children,
                    Clinical Practice with Couples and Families,
                    Clinical Practice with Groups,
                    Integrative Psychotherapy,
                    Dynamic Psychotherapy,
                    Clinical Practice with Adolescents,
                    Clinical Practice with the Elderly,
                    Mental Illness: Clinical Issues and Practice,
                    Clinical Practice in Schools,
                    Clinical Practice with Immigrants,
                    Interdisciplinary Perspectives in Health Care Ethics,
                </p>
            </div>

            <div className='py-2'>
                <h2 className='font-medium text-[#91000D] py-2'>Current Issue:</h2>
                <div>
                    <SociologyArtics></SociologyArtics>
                </div>
            </div>
        </div>
    );
};

export default SociologyScope;